"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Check, Clock3, KeyRound, LockKeyhole, Pause, Play, RotateCcw, Square, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
type Challenge={id:number;area:string;company:string;context:string;problem:string;mission:string[]};
type TimerState={status:"idle"|"running"|"paused"|"finished";duration:number;remaining:number;endAt:number|null};
type BoardState={selected:number[];ownChallenge:Challenge|null;teamName:string|null;round:number;timer:TimerState;serverNow:number};
function deviceId(){let id=localStorage.getItem("painel-device-id");if(!id){id=crypto.randomUUID();localStorage.setItem("painel-device-id",id)}return id}
export default function Home(){
 const [team,setTeam]=useState("");const [confirmed,setConfirmed]=useState("");const [state,setState]=useState<BoardState>({selected:[],ownChallenge:null,teamName:null,round:1,timer:{status:"idle",duration:300,remaining:300,endAt:null},serverNow:Date.now()});const [candidate,setCandidate]=useState<number|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [admin,setAdmin]=useState(false);const [pin,setPin]=useState("");const [minutes,setMinutes]=useState("5");const [clock,setClock]=useState(Date.now());const [currentPin,setCurrentPin]=useState("");const [newPin,setNewPin]=useState("");const [confirmPin,setConfirmPin]=useState("");
 const refresh=useCallback(async()=>{const r=await fetch(`/api/board?device=${encodeURIComponent(deviceId())}`,{cache:"no-store"});if(!r.ok)return;const next=await r.json() as BoardState;setState(next);if(next.teamName)setConfirmed(next.teamName);setLoading(false)},[]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,2000);return()=>clearInterval(timer)},[refresh]);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),250);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"get_board_status",title:"Consultar painel",description:"Consulta a rodada atual, as casas escolhidas e as que continuam disponíveis.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},async execute(){const r=await fetch(`/api/board?device=${encodeURIComponent(deviceId())}`,{cache:"no-store"});if(!r.ok)throw new Error("Painel indisponível");const next=await r.json() as BoardState;setState(next);return{round:next.round,selected:next.selected,available:Array.from({length:16},(_,i)=>i+1).filter(id=>!next.selected.includes(id))}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 const progress=useMemo(()=>state.selected.length/16*100,[state.selected.length]);
 const secondsLeft=state.timer.status==="running"&&state.timer.endAt?Math.max(0,Math.ceil((state.timer.endAt-clock)/1000)):state.timer.status==="finished"?0:state.timer.remaining;
 const timeText=`${String(Math.floor(secondsLeft/60)).padStart(2,"0")}:${String(secondsLeft%60).padStart(2,"0")}`;
 async function choose(){if(!candidate||!confirmed)return;setMessage("");const r=await fetch("/api/board",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cardId:candidate,teamName:confirmed,deviceId:deviceId()})});const data=await r.json();if(!r.ok){setMessage(data.error||"Esta casa acabou de ser escolhida.");setCandidate(null);await refresh();return}setCandidate(null);await refresh()}
 async function reset(){const r=await fetch("/api/reset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin})});if(!r.ok){setMessage("Senha incorreta.");return}localStorage.removeItem("painel-device-id");setConfirmed("");setTeam("");setPin("");setAdmin(false);setMessage("Painel reiniciado para uma nova turma.");await refresh()}
 async function nextRound(){const r=await fetch("/api/round",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin})});if(!r.ok){setMessage("Senha incorreta.");return}setPin("");setAdmin(false);setMessage("Nova rodada liberada para todas as equipes.");await refresh()}
 async function timerAction(action:"start"|"pause"|"resume"|"clear"){const r=await fetch("/api/timer",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin,action,minutes:Number(minutes)})});if(!r.ok){setMessage("Senha incorreta ou tempo inválido.");return}await refresh()}
 async function changePassword(){if(newPin!==confirmPin){setMessage("A confirmação da nova senha não confere.");return}const r=await fetch("/api/password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({currentPin,newPin})});const data=await r.json();if(!r.ok){setMessage(data.error||"Não foi possível alterar a senha.");return}setPin(newPin);setCurrentPin("");setNewPin("");setConfirmPin("");setMessage("Senha do professor alterada com sucesso.")}
 return <main className="min-h-screen bg-[#f4f6f8] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#174f78] text-white"><Building2/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#174f78]">Técnico em Administração</p><h1 className="text-lg font-extrabold sm:text-2xl">Painel de Desafios Empresariais</h1></div></div><div className="flex items-center gap-2">{state.timer.status!=="idle"&&<div className={`flex items-center gap-2 rounded-xl px-3 py-2 font-black tabular-nums ${secondsLeft===0?"bg-red-100 text-red-700":"bg-[#fff4e4] text-[#845014]"}`}><Clock3 className="size-5"/>{secondsLeft===0?"Tempo encerrado":timeText}</div>}<Button variant="outline" size="sm" onClick={()=>setAdmin(true)}><LockKeyhole className="size-4"/>Professor</Button></div></div></header>
 <section className="mx-auto max-w-6xl px-4 py-6 sm:px-6"><div className="mb-6 grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-[1fr_auto] md:items-center"><div><div className="mb-2 flex items-center gap-2 font-bold"><Users className="size-5 text-[#e28b22]"/>Identificação da equipe</div>{confirmed?<p className="text-slate-600">Equipe: <strong className="text-slate-950">{confirmed}</strong> · <span className="font-bold text-[#174f78]">Rodada {state.round}</span></p>:<div className="flex max-w-xl gap-2"><Input value={team} onChange={e=>setTeam(e.target.value)} placeholder="Digite o nome da equipe" maxLength={40}/><Button className="bg-[#174f78] hover:bg-[#123f61]" disabled={!team.trim()} onClick={()=>setConfirmed(team.trim())}>Entrar</Button></div>}</div><div className="min-w-52"><div className="mb-2 flex justify-between text-sm font-semibold"><span>{state.selected.length} escolhidas</span><span>{16-state.selected.length} disponíveis</span></div><Progress value={progress}/></div></div>
 {message&&<p role="status" className="mb-4 rounded-xl bg-amber-50 px-4 py-3 font-medium text-amber-900">{message}</p>}
 {state.ownChallenge?<ChallengeView challenge={state.ownChallenge} team={state.teamName||confirmed}/>:<><div className="mb-4"><h2 className="text-2xl font-black">Escolha uma casa</h2><p className="text-slate-600">Cada equipe pode abrir apenas um desafio. A casa escolhida ficará bloqueada para toda a turma.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{Array.from({length:16},(_,i)=>i+1).map(id=>{const used=state.selected.includes(id);return <button key={id} disabled={used||!confirmed||loading} onClick={()=>setCandidate(id)} className={`relative aspect-[.78] rounded-2xl border-2 p-3 text-left transition ${used?"cursor-not-allowed border-slate-200 bg-slate-200 text-slate-500":"border-[#174f78] bg-white shadow-[0_6px_0_#174f78] hover:-translate-y-1 hover:shadow-[0_10px_0_#174f78] active:translate-y-1 active:shadow-none"}`}><span className="text-xs font-extrabold uppercase tracking-widest">Casa</span><strong className="block text-4xl font-black sm:text-5xl">{String(id).padStart(2,"0")}</strong><span className={`absolute bottom-3 left-3 right-3 rounded-lg px-2 py-1 text-center text-xs font-bold uppercase ${used?"bg-slate-300":"bg-[#f4a340] text-slate-950"}`}>{used?<><Check className="mr-1 inline size-3"/>Escolhida</>:"Disponível"}</span></button>})}</div></>}
 </section><Dialog open={candidate!==null} onOpenChange={o=>!o&&setCandidate(null)}><DialogContent><DialogHeader><DialogTitle>Confirmar a casa {String(candidate||0).padStart(2,"0")}?</DialogTitle><DialogDescription>Após a confirmação, sua equipe não poderá selecionar outra casa.</DialogDescription></DialogHeader><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setCandidate(null)}>Voltar</Button><Button className="bg-[#174f78] hover:bg-[#123f61]" onClick={choose}>Confirmar escolha</Button></div></DialogContent></Dialog>
 <Dialog open={admin} onOpenChange={setAdmin}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Área do professor</DialogTitle><DialogDescription>Controle as rodadas, o cronômetro e a senha de acesso.</DialogDescription></DialogHeader><Input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Senha do professor"/><section className="rounded-xl border p-4"><h3 className="mb-3 flex items-center gap-2 font-bold"><Clock3 className="size-5 text-[#174f78]"/>Cronômetro compartilhado</h3><div className="mb-3 flex items-center gap-2"><Input type="number" min="1" max="180" value={minutes} onChange={e=>setMinutes(e.target.value)} aria-label="Tempo em minutos"/><span className="text-sm font-semibold text-slate-600">minutos</span></div><div className="grid grid-cols-2 gap-2"><Button className="bg-[#174f78] hover:bg-[#123f61]" onClick={()=>timerAction("start")}><Play className="size-4"/>Iniciar</Button>{state.timer.status==="paused"?<Button variant="outline" onClick={()=>timerAction("resume")}><Play className="size-4"/>Continuar</Button>:<Button variant="outline" onClick={()=>timerAction("pause")}><Pause className="size-4"/>Pausar</Button>}<Button variant="outline" className="col-span-2" onClick={()=>timerAction("clear")}><Square className="size-4"/>Zerar cronômetro</Button></div></section><Button className="bg-[#174f78] hover:bg-[#123f61]" onClick={nextRound}>Liberar próxima rodada</Button><section className="rounded-xl border p-4"><h3 className="mb-3 flex items-center gap-2 font-bold"><KeyRound className="size-5 text-[#174f78]"/>Alterar senha</h3><div className="space-y-2"><Input type="password" inputMode="numeric" value={currentPin} onChange={e=>setCurrentPin(e.target.value)} placeholder="Senha atual"/><Input type="password" inputMode="numeric" value={newPin} onChange={e=>setNewPin(e.target.value)} placeholder="Nova senha (4 a 8 números)"/><Input type="password" inputMode="numeric" value={confirmPin} onChange={e=>setConfirmPin(e.target.value)} placeholder="Confirmar nova senha"/><Button variant="outline" className="w-full" onClick={changePassword}>Salvar nova senha</Button></div></section><Button variant="destructive" onClick={reset}><RotateCcw className="size-4"/>Reiniciar painel</Button></DialogContent></Dialog></main>}
function ChallengeView({challenge,team}:{challenge:Challenge;team:string}){return <article className="mx-auto max-w-3xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><div className="bg-[#174f78] px-6 py-5 text-white"><p className="text-sm font-bold uppercase tracking-[.18em]">Desafio da equipe {team}</p><div className="mt-2 flex items-end justify-between gap-4"><div><span className="rounded-full bg-white/15 px-3 py-1 text-sm font-bold">{challenge.area}</span><h2 className="mt-3 text-2xl font-black sm:text-4xl">{challenge.company}</h2></div><strong className="text-5xl font-black text-[#f4a340]">{String(challenge.id).padStart(2,"0")}</strong></div></div><div className="space-y-5 p-6"><p className="text-lg leading-relaxed text-slate-700">{challenge.context}</p><section className="rounded-2xl border-l-8 border-[#f4a340] bg-amber-50 p-5"><h3 className="mb-2 text-lg font-black">Situação-problema</h3><p>{challenge.problem}</p></section><section className="rounded-2xl border-l-8 border-[#174f78] bg-sky-50 p-5"><h3 className="mb-2 text-lg font-black">Missão da equipe</h3>{challenge.mission.map(i=><p key={i} className="mb-2 last:mb-0">• {i}</p>)}</section><div className="rounded-xl bg-slate-100 px-4 py-3 text-center font-semibold text-slate-600">Resolva o desafio e aguarde o professor liberar a próxima rodada.</div></div></article>}
