export const challenges=[
{id:1,area:"Planejamento Estratégico",company:"Padaria Pão na Praça",context:"A padaria atua há mais de quinze anos no mesmo bairro. Um novo concorrente passou a oferecer preços mais baixos e entrega, e as vendas diminuíram.",problem:"O empresário quer investir em melhorias, mas não sabe quais decisões tomar primeiro nem quais objetivos priorizar.",mission:["Que informações vocês levantariam antes de tomar qualquer decisão?","Como organizariam um plano para ajudar essa empresa?"]},
{id:2,area:"Gestão de Projetos",company:"Academia Movimento",context:"A academia promoverá, em dois meses, um grande evento de saúde e qualidade de vida com parceiros, convidados e atividades abertas ao público.",problem:"Existem muitas tarefas, mas ninguém sabe exatamente quem será responsável por cada atividade ou qual deve ser feita primeiro.",mission:["Como vocês organizariam esse evento?","Como garantiriam que todas as etapas fossem concluídas no prazo?"]},
{id:3,area:"Recrutamento e Seleção",company:"Cafeteria Aroma",context:"Após conquistar novos clientes, a cafeteria abriu duas vagas para atendente e recebeu mais de cem currículos.",problem:"A empresa precisa escolher os candidatos mais adequados para integrar sua equipe.",mission:["Como vocês escolheriam os candidatos?","Quais critérios utilizariam para tomar essa decisão?"]},
{id:4,area:"Cargos, Salários e Desenvolvimento",company:"Loja Estilo",context:"A loja cresceu rapidamente. Alguns funcionários reclamam que pessoas com atividades semelhantes recebem salários diferentes e não sabem como podem crescer profissionalmente.",problem:"O proprietário deseja tornar a gestão de pessoas mais transparente e motivadora.",mission:["Como vocês investigariam essa situação?","O que poderia ser feito para valorizar os colaboradores?"]},
{id:5,area:"Saúde e Segurança",company:"Hospital Vida",context:"O hospital percebeu um aumento no número de acidentes de trabalho e afastamentos nos últimos meses.",problem:"A direção acredita que algumas práticas colocam funcionários em risco e deseja tornar o ambiente mais seguro.",mission:["Quais fatores podem estar causando o problema?","Que ações melhorariam a segurança e a qualidade de vida dos trabalhadores?"]},
{id:6,area:"Admissão e Demissão",company:"Escritório Contábil Alfa",context:"O escritório contratou e desligou funcionários recentemente. Durante os processos, parte da documentação foi preenchida incorretamente.",problem:"A empresa está preocupada com possíveis problemas legais e administrativos.",mission:["Quais consequências essa situação pode gerar?","Como evitar erros em processos de admissão e demissão?"]},
{id:7,area:"Cálculos Trabalhistas",company:"Indústria Metal Forte",context:"Colaboradores procuraram o RH com dúvidas sobre férias, horas extras e verbas rescisórias após encontrarem valores incorretos.",problem:"A empresa precisa garantir cálculos corretos para evitar prejuízos e reclamações.",mission:["Por que esses cálculos precisam ser precisos?","Como evitar erros na folha de pagamento?"]},
{id:8,area:"Gestão de Materiais",company:"Distribuidora Central",context:"Com o aumento das vendas, alguns produtos passaram a faltar enquanto outros permanecem estocados por muito tempo.",problem:"A empresa enfrenta desperdícios, falta de mercadorias e dificuldades para atender clientes.",mission:["O que pode estar causando o problema?","Como organizariam o controle dos materiais?"]},
{id:9,area:"Logística de Distribuição",company:"E-commerce Conecta",context:"As vendas cresceram, mas também aumentaram as reclamações sobre atrasos e erros nas entregas.",problem:"A empresa perde clientes porque pedidos chegam fora do prazo ou no endereço errado.",mission:["Quais fatores podem causar esses problemas?","Como tornar a distribuição mais eficiente?"]},
{id:10,area:"Comércio Exterior",company:"Importadora Global Trade",context:"A empresa pretende importar equipamentos tecnológicos pela primeira vez para ampliar sua linha de produtos.",problem:"Os gestores desconhecem os procedimentos e temem erros que atrasem ou inviabilizem a compra.",mission:["Quais cuidados tomariam antes da negociação?","Quais desafios existem na compra de produtos de outro país?"]},
{id:11,area:"Marketing",company:"Sorveteria Verão",context:"A sorveteria tem grande movimento no verão, mas nos demais meses o número de clientes diminui drasticamente.",problem:"O proprietário deseja aumentar as vendas durante todo o ano e tornar a marca mais conhecida.",mission:["Que ações sugeririam para atrair clientes?","Como divulgar a empresa de forma eficiente?"]},
{id:12,area:"Processos Comerciais",company:"Loja Tech Solutions",context:"Alguns vendedores conseguem ótimos resultados, enquanto outros têm dificuldade para fechar vendas.",problem:"A empresa deseja organizar o atendimento e oferecer uma experiência semelhante para todos os clientes.",mission:["O que diferencia um bom atendimento?","Como padronizar o processo de vendas?"]},
{id:13,area:"Crédito e Cobrança",company:"Financeira Confiança",context:"Nos últimos meses, aumentou significativamente o número de clientes que deixaram de pagar suas parcelas.",problem:"A empresa precisa reduzir a inadimplência sem comprometer o relacionamento com os clientes.",mission:["Como decidir para quem conceder crédito?","Como cobrar mantendo uma boa relação com o cliente?"]},
{id:14,area:"Tesouraria, Contas a Pagar e Receber",company:"Restaurante Sabor da Casa",context:"O restaurante tem bom faturamento, mas atrasa pagamentos e enfrenta dificuldades para manter dinheiro disponível em caixa.",problem:"Os gestores precisam entender por que a empresa vende bem, mas ainda enfrenta problemas financeiros.",mission:["Por que isso pode acontecer?","Que atitudes recomendariam para enfrentar o problema financeiro?"]},
{id:15,area:"Custos e Precificação",company:"Padaria Pão Quente",context:"A padaria vende muito, mas o proprietário percebe que o lucro é muito menor do que esperava.",problem:"Alguns produtos podem estar sendo vendidos por preços que não cobrem todos os custos.",mission:["Que informações analisariam antes de decidir?","Como aumentar o lucro sem afastar os clientes?"]},
{id:16,area:"Qualidade em Serviços",company:"Hotel Bela Vista",context:"Alguns hóspedes elogiam o hotel; outros reclamam da demora no check-in, da limpeza e das diferenças no atendimento.",problem:"A direção deseja oferecer uma experiência de qualidade independentemente do dia ou do colaborador.",mission:["Como melhorar continuamente os processos?","Como garantir um padrão de qualidade nos serviços?"]}
] as const;
